### ISSUE TITLE
YIN and YANG model differencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mbj4668/pyang#112] opened 2015-03-16 07:50 UTC
```
What steps will reproduce the problem?
1. pyang ietf-system-tls-auth.yin ietf-system.yin (error)
2. generate YANG modules from these two models
3. pyang ietf-system-tls-auth.yang ietf-system.yang (success)

What is the expected output? What do you see instead?

I would expect the same output for 1. and 3.

What version of the product are you using? On what operating system?

The newest pyang version pulled from the SVN repository.


```

Original issue reported on code.google.com by `mv6...@gmail.com` on 13 Oct 2014 at 10:55

Attachments:
* [models.zip](https://storage.googleapis.com/google-code-attachments/pyang/issue-112/comment-0/models.zip)

**Comment by mbj4668** [comment] 2015-10-01 10:54
I cannot reproduce this anymore, closing/

**Closed by mbj4668** 2015-10-01 10:54 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
