### ISSUE TITLE
Yang Deprecated node

### ISSUE THREAD

**Issue by masif-cs** [mbj4668/pyang#577] opened 2020-03-12 07:14 UTC
Hi,

Pyang is not able to decode deprecated node properly. If a container/List is deprecated, all leaf/leaf-list present inside that will also be deprecated automatically. But the pyang tree output is not giving that result. It is just showing a Container/List as "x--" in yang tree but all the nodes inside that is showing as "+--" which is not correct.
Can you please let me know if the problem is fixed or yet to be fixed.

**Comment by fredgan** [comment] 2020-03-12 07:46
Seems you are right. I will try to fix this. If fixed, I will at you.

**Comment by mbj4668** [comment] 2020-03-12 11:16
Actually, I don't think this is a bug.  In YANG, if a container is marked as deprecated, its children are NOT automatically also deprecated.  You need to explicitly mark them as well.

**Comment by masif-cs** [comment] 2020-03-12 11:26
Yes you are right. Each child has to marked as deprecated when Container is marked deprecated. But in case when it use "uses" keyword for grouping, it cant mark that grouping as deprecated because at one place that grouping is current and other place it will be obsolete/deprecated. Example given below:
**YANG Input:**
list per-band-config {
      key band-number;
      config false;
      status deprecated;
      description "beamforming information per band";
      uses per-band-config-element;
    }
**YANG Tree Output:**
x--ro per-band-config* [band-number]
     |  +--ro band-number          -> /o-ran-module-cap:module-capability/band-capabilities/band-number
     |  +--ro tx-array*            -> /o-ran-uplane-conf:user-plane-configuration/tx-arrays/name
     |  +--ro rx-array*            -> /o-ran-uplane-conf:user-plane-configuration/rx-arrays/name
     |  +--ro static-properties
     |  |  +--ro rt-bf-weights-update-support?   boolean

**Comment by masif-cs** [comment] 2020-03-16 06:53
Hi @fredgan ,

Can you please let know when can I expect this issue fixed.

**Comment by fredgan** [comment] 2020-03-16 07:27
@masif-cs Hi, sorry for not quite understood. But I undertand now. 

In fact, there are a `status` substatement for `uses` statements for your purpose. If the `status` is for marking nodes in grouping, there is an other bug for tree printing as I printed and find it doesn't work. 

But I am not sure if this is correct. So Maybe I need Martin's confirm. @mbj4668 

If yes, I will fix it as soon as possible.

**Comment by mbj4668** [comment] 2020-03-18 08:19
No this is not a bug in pyang.  In YANG, a node's "status" is not inherited from the parent, and it is not inherited by its children.  Each definition has its own "status", by design.

However, it would probably be useful to print a warning if e.g. a container is "deprecated" and a child is "current", etc.

**Closed** 2020-04-07 06:52 UTC
