### ISSUE TITLE
xml skeleton generation of augmented yang models

### ISSUE THREAD

**Issue by GiacomoCortesi** [mbj4668/pyang#749] opened 2021-06-22 13:53 UTC
Hi guys,

I've been trying to generate the xml skeleton for augmented yang models, but it always result in an empty XML generated.
Looking at the code, the reason is simply because it tries to render the i_children of the augmenting yang model, but being an empty list it results in an empty XML.
However, the augmentation statements are added already to the yang model being augmented, therefore it would be sufficient to parse that instead of the augmenting yang model and it would work.

I have a working patch of the code, if anyone may be interested I'd be happy to open a PR (and/or provide a more detailed explanation with examples)

**Comment by llhotka** [comment] 2021-06-23 10:52
This may be a duplicate of #371. If not, please provide an example.

**Comment by GiacomoCortesi** [comment] 2021-06-23 12:35
yes it is a duplicate, thank you, it's clear now.

**Closed** 2021-06-23 12:34 UTC
