### ISSUE TITLE
Enum Data Type resolution in pyang tree output

### ISSUE THREAD

**Issue by masif-cs** [mbj4668/pyang#654] opened 2020-07-09 06:40 UTC
Hi,

I am generating pyang tree output for yang models. But it has too many enumeration whose data type needs to be resolved. Is there anyway by which I can know the data type directly in pyang tree output?

Eg:
leaf **rw-duplex-scheme** {
      type leafref {
        **path "/user-plane-configuration/tx-array-carriers[name=current()/../name]" + "/duplex-scheme";**
        require-instance false;
      }
      description
        "Config true type of duplex scheme.";
    }

Pyang Tree:
     |  +--ro **duplex-scheme**?                 **enumeration**
     |  +--rw **rw-duplex-scheme**?              -> /user-plane-configuration/tx-array-carriers[name=current()/../name]/duplex-scheme

After resolving the leafref I am getting enumeration instead of the data type. Can I get the data-type directly for duplex-scheme instead of enumeration?

**Comment by fredgan** [comment] 2020-07-09 07:03
Hi @masif-cs , sorry I don't understand. What's the data-type of `duplex-scheme`? I mean what do you expect exactly to replace the `enumeration`.

**Comment by masif-cs** [comment] 2020-07-09 07:06
Hi @fredgan,

It should be the data type of the node like string, integer or if it is enum then ENUM values like FDD/TDD for duplex-scheme.

leaf duplex-scheme {
      type **enumeration** {
        **enum TDD** {
              description
                "TDD scheme";
            }
        **enum FDD** {
              description
                "FDD scheme";
        }
      }
      config false;

      description
        "Type of duplex scheme O-RU supports.";
    }

**Comment by fredgan** [comment] 2020-07-09 07:13
Hi @masif-cs 

I think you misunderstand the type `enumeration`.

`enumeration` is type,  and `TDD`/`FDD` are values of the `enumeration` type.  It's just like `int` is type,  and `100` is the value of `int` type.

So, I don't think `TDD`/`FDD` can be after `duplex-scheme`

**Comment by masif-cs** [comment] 2020-07-09 07:20
Hi @fredgan 

The problem here is yang model has too many enumeration. Now it is difficult to map which enumeration belongs to what?

For eg:
  |     +--rw link-up-down-trap-enable?     enumeration {if-mib}?
  |     +--ro admin-status                  enumeration {if-mib}?
  |     +--ro oper-status                   enumeration

Now above all say enumeration but can have different values of enumeration. Now it is difficult to find where are they coming from whether it is from some grouping or some other yang types etc. So if we get some reference like grouping_name_enumeration so that we can map it properly.

**Comment by fredgan** [comment] 2020-07-09 08:03
OK, I get it.

You can easily modify the plugin `tree` to reach your point. 

Here is an example:

https://github.com/mbj4668/pyang/blob/c91c20723c9a59b07c899b1deac1cb8fa22166f6/pyang/plugins/tree.py#L585

modify the line to like:

```py
585                if t.arg == "enumeration":
586                    ret = t.arg + "{ "
587                    for substmt in t.substmts:
588                        ret = ret + substmt.arg + " "
589                    ret = ret + " }"
590                    return ret
591                else:
592                    return t.arg
```

**Comment by masif-cs** [comment] 2020-07-09 13:02
Hi @fredgan 

After the changes, I compiled using command given on main page. I dont see any difference in the output. Am I doing something wrong?

**Comment by fredgan** [comment] 2020-07-09 13:25
Hi,
Maybe you are still using your old pyang, maybe you have some typo, such as wrong spelling `enumeration`. Anyway, you can try to debug it using pycharm or some IDE other.

**Comment by masif-cs** [comment] 2020-07-09 14:25
Hi,

I am not so familiar with pycharm. I can see there is no typo.

I have downloaded the latest version and made changes:
pyang --version
pyang 2.3.2

Below are the changes:
    584             else:
    585                 if t.arg == "enumeration":
    586                     ret = t.arg + "{ "
    587                     for substmt in t.substmts:
    588                         ret = ret + substmt.arg + " "
    589                     ret = ret + " }"
    590                     return ret
    591                 else:
    592                     return t.arg

Output after changes in pyang and compiling again:
     |  +--ro duplex-scheme?                 enumeration
     |  +--rw rw-duplex-scheme?              -> /user-plane-configuration/tx-array-carriers[name=current()/../name]/duplex-scheme

Yang Model:
leaf **duplex-schem**e {
      type **enumeration** {
        enum **TDD** {
              description
                "TDD scheme";
            }
        enum **FDD** {
              description
                "FDD scheme";
        }
      }
      config false;

      description
        "Type of duplex scheme O-RU supports.";
    }
    leaf **rw-duplex-scheme** {
      type leafref {
        path "**/user-plane-configuration/tx-array-carriers[name=current()/../name]" + "/duplex-scheme**";
        require-instance false;
      }
      description
        "Config true type of duplex scheme.";
    }

What is the expected output? What I am missing? Please help me out in solving this problem.

**Comment by fredgan** [comment] 2020-07-10 01:18
Well.

I use the code above. And my YANG model is
```yang
module mod3 {
    namespace "urn:f";
    prefix f;

    typedef f_type {
        type enumeration {
            enum "foo";
            enum "bar";
        }
    }

    container b {
        leaf q {
            type f_type;
        }
        leaf q2 {
            type enumeration {
                enum "enum1" {
                    description "enum 1";
                }
                enum "enum2";
            }
        }
    }
}
```

The output is:
```
module: mod3
  +--rw b
     +--rw q?    f_type
     +--rw q2?   enumeration{ enum1 enum2  }
```

I'm not sure where the issue is in your case. 

Maybe you can try to download the pyang-2.3.2, then modify  `plugins/tree.py`, then `source ./env.sh`, run your model.

**Comment by masif-cs** [comment] 2020-07-10 05:58
Hi @fredgan 

I was able to resolve the issue. My code was not hitting else case because prefix_with_modname was coming TRUE all the time. So I moved the logic to line 574. Two more things I need you help on:

1. Is it possible to resolve typedef?
2. Is it possible to print the value of enum also? Example below:
leaf status {
        type enumeration {
          enum "Successful" {
            **value 1;**
          }
          enum "Failed" {
            **value 2;**
          }
        }

Thanks for your help

**Comment by fredgan** [comment] 2020-07-10 06:16
Hi, 

It's also not hard. Remember that the original YANG statements are organized in tree by the property of `substmts`.

So, for the second question, you just need another level search for the substmt for the 'value'.

But for the first question, it has a bit more work, but it's not hard. I believe you can solve it.

**Comment by masif-cs** [comment] 2020-07-10 06:44
Hi,

Could you please help me out with the logic? I dont know python and new to pyang code.
Do I need to do like this?
if t.arg == "enumeration":
                        ret = t.arg + "{"
                        for substmt in t.substmts:
                            ret = ret + substmt.arg + ","
                            **for stmt in substmt.substmts:
                                if stmt.arg == "value":
                                    ret = ret + ??**
                        ret = ret + "}"
                        return ret
                    else:
                        return t.arg

**Comment by fredgan** [comment] 2020-07-10 07:23
Hi, I rewrite my modification to follow to fit your request.

```py
                def find_type(tt):
                    if tt.arg == "enumeration":
                        ret = tt.arg + "{ "
                        for substmt in tt.substmts:
                            vs = substmt.search_one('value')
                            if vs is None:
                                ret = ret + substmt.arg + " "
                            else:
                                ret = ret + substmt.arg + ":" + vs.arg + " "  # add value after enum
                        ret = ret + "}"
                        return ret
                    elif tt.arg in ("boolean","binary","bits","decimal64","empty", "identityref",
                                   "instance-identifier","int8","int16","int32","int64",
                                   "leafref","string" ,"uint8","uint16","uint32","uint64","union"):
                        return tt.arg
                    else:
                        typedef = t.i_typedef
                        typedeftype = typedef.search_one('type')
                        if typedeftype is None:
                            return tt.arg
                        else:
                            return find_type(typedeftype)  # find typedef recursive
                return find_type(t)
```
Just replace the original Line585. 

But I don't garantee my code works in all situation since it's not test fully.

**Comment by fredgan** [comment] 2020-07-13 13:30
Just closing. If you still have some questions, please reopen it.

**Closed** 2020-07-13 13:30 UTC
