### ISSUE TITLE
--ietf, validation of RFC 8407 needs to be updated

### ISSUE THREAD

**Issue by yingzhenqu** [mbj4668/pyang#773] opened 2021-11-30 18:00 UTC
PYANG with "--ietf" option is throwing a warning for the new license statement:
yqu@Ys-MacBook-Pro yang % pyang --ietf ietf-nmda-compare.yang
ietf-nmda-compare.yang:60: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

The validation of IETF rules found in RFC 8407 needs to be updated. "the Simplified BSD License" should be changed to "the Revised BSD License" as suggested below:

New:
  Redistribution and use in source and binary forms, with or
  without modification, is permitted pursuant to, and subject to
  the license terms contained in, **_the Revised BSD License_** set
  forth in Section 4.c of the IETF Trust's Legal Provisions
  Relating to IETF Documents
  (https://trustee.ietf.org/license-info).

Old:
  Redistribution and use in source and binary forms, with or
  without modification, is permitted pursuant to, and subject to
  the license terms contained in, the Simplified BSD License set
  forth in Section 4.c of the IETF Trust's Legal Provisions
  Relating to IETF Documents
  (https://trustee.ietf.org/license-info).

Detail info about the license can be found here:https://trustee.ietf.org/documents/trust-legal-provisions/tlp-5/

**Comment by mbj4668** [comment] 2021-11-30 18:24
duplicate of #770

**Closed by mbj4668** 2021-11-30 18:24 UTC
