### ISSUE TITLE
DSDL plugin  fails for unique within groupings

### ISSUE THREAD

**Issue by paulo-g** [mbj4668/pyang#458] opened 2019-01-25 13:34 UTC
For the model:

```
module test {
    namespace "http://test.com";
    prefix test;

    grouping g {
      list l {
        unique a;
        key b;

        leaf a {type string;}
        leaf b {type string;}
      }
    }

    uses g;
}
```

Running the dsdl plugin:

> pyang -f dsdl test.yang

raise an exception:
```
...translators/dsdl.py", line 1158, in addpref
    ns, node_name = self.add_prefix(node, stmt).split(":")
ValueError: need more than 1 value to unpack
```

It seems the add_prefix method is not actually doing anything if within a grouping, but here it needs to do it.

Using python 2.7.5 and pyang 1.7.8.
Problem was not visible in pyang 1.7.5!!!

**Comment by paulo-g** [comment] 2019-01-25 16:53
Seems like a direct consequence of commit https://github.com/mbj4668/pyang/commit/be1b3c73ae7c5220d6f25f7567a0e57ff0a61059 .

**Comment by llhotka** [comment] 2019-01-29 15:50
Yes, this issue was caused by commit be1b3c7 (part of PR #434). I asked the author to have a look.

**Comment by nvarkonyi** [comment] 2019-01-30 09:47
I'm checking it now.

**Comment by nvarkonyi** [comment] 2019-01-30 15:27
Added a pull request fixing this issue: https://github.com/mbj4668/pyang/pull/461
Previously I missed the fact that 'add_prefix' does not add prefix for global groupings.

**Comment by mbj4668** [comment] 2019-04-25 09:12
PR has been merged

**Closed by mbj4668** 2019-04-25 09:12 UTC
