### ISSUE TITLE
submodule augmenting main module

### ISSUE THREAD

**Issue by apoorvashastry** [mbj4668/pyang#794] opened 2022-01-18 21:32 UTC
Pyang throws error if a submodule is augmenting a node from main module 
```
- CRITICAL ERROR line 13: node module1::test is not found
- CRITICAL ERROR line 16: module1-sub:test in the path for ref-id at /home/owner/tmp/yangsuite/yangsuite/users/owner/repositories/test-circular/module1-sub@2017-10-02.yang:14 is not found
```
I think in YANG 1.1 a submodule can augment main module. But still pyang reports error. Am I missing anything here or the model definition is wrong?

module1.yang:
```
module module1 {
    namespace "http://module1";
    prefix module1;
    yang-version 1.1;
    include module1-sub;
    revision 2017-09-30 {
        description "Initial release 1";
    }
    container test {
        leaf id {
            type enumeration {
                enum "option1";
                enum "option2";
            }
        }
        leaf copy-of-id {
            type leafref {
                path "../id";
            }
        }
    }
}
```

module1-sub.yang:

```
submodule module1-sub {
    belongs-to "module1" {
        prefix "module1";
    }
    yang-version 1.1;
    revision 2017-10-02 {
        description "Initial release 1";
    }
    augment /module1:test {
        leaf ref-id {
            type leafref {
                path "/module1:test/id";
            }
        }
    }
}
```

**Comment by mbj4668** [comment] 2022-01-19 12:05
This is a known issue.  Closing as duplicate of #323.

**Closed by mbj4668** 2022-01-19 12:05 UTC

**Comment by apoorvashastry** [comment] 2022-01-19 17:41
@mbj4668 : What's the resolution or workaround for this? I looked into the #323 before opening this issue. I didn't quite what's the workaround is. Can you please elaborate?
