### ISSUE TITLE
New Requirement: Where can I get the document how to develop a plugin for PYang?

### ISSUE THREAD

**Issue by zhangliya007** [mbj4668/pyang#295] opened 2016-12-30 10:19 UTC
Where can I get the document how to develop a plugin for PYang? Thanks.

**Comment by mbj4668** [comment] 2017-01-26 10:12
See issue #257.

**Comment by mbj4668** [comment] 2017-03-17 09:00
closing as duplicate of #257.

**Closed by mbj4668** 2017-03-17 09:00 UTC
Labels: duplicate
